use_frameworks!

platform :ios, '10.0'

target 'PodRepo_Example' do
  pod 'PodRepo', :path => '../'

  target 'PodRepo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
